CREATE TABLE Subcategories
(
    Id         INT PRIMARY KEY IDENTITY(1,1),
    Name       NVARCHAR(100) NOT NULL,
    CategoryId INT FOREIGN KEY REFERENCES Categories(Id) ON DELETE CASCADE
);

ALTER TABLE Transactions
    ADD SubcategoryId INT FOREIGN KEY REFERENCES Subcategories(Id) ON DELETE CASCADE;